version : "3.9"
services :
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend_prod:local
    env_file:
      - ./.env
    networks:
      - pongnet
    depends_on:
      database:
        condition: service_healthy
    expose:
      - 3001
      - 3004
    init: true
    restart: always
    
  nginx :
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx_prod:local
    networks:
      - pongnet
      - dokploy-network
    depends_on:
      - backend
    ports:
      - 8000:8080
    init: true
    restart: always
   
networks:
  pongnet:
  dokploy-network:
    external: true
  
