FROM node:18-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY --chown=node:node ./code/package*.json ./

RUN npm ci

COPY --chown=node:node ./code ./

USER node

CMD ["sh", "-c", "npx prisma studio & npm run start:dev"]
